# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: deploy to aliyun 

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy
      # 使用此action，也可在官方市场选择其他action
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        # Private Key secrets.ALIYUN就是刚才配置的密钥名
        SSH_PRIVATE_KEY: ${{ secrets.ALIYUN }}
        # For any initial/required rsync flags
        ARGS:  "-rltgoDzvO --delete"
        # Source directory dist/ 需要到远端服务器的文件目录 **填入自己的打包路径**
        SOURCE: "dist/"
        # Remote host **填入自己的域名**
        REMOTE_HOST: "123.56.115.27"
        # Remote user **填入自己的用户,一般都是root用户**
        REMOTE_USER: "root"
        # Target directory 此处填写的是我博客域名下的action pacth下 **填入自己的域名路径**
        TARGET: "java/springboot"
